// PLEASE DO NOT EDIT THIS FILE!!!
// This file is auto-generated.
// To regenerate all of these *Sim.java files, run the following from the WPIWebSockets folder:
// npx -p @asyncapi/generator ag --force-write -o ./src/main/java/org/team199/wpiws/devices asyncapi-template/wpilib-ws.yaml asyncapi-template/
package org.team199.wpiws.devices;

import java.util.HashMap;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

import org.team199.wpiws.ScopedObject;
import org.team199.wpiws.StateDevice;
import org.team199.wpiws.connection.ConnectionProcessor;
import org.team199.wpiws.connection.WSValue;
import org.team199.wpiws.interfaces.*;

/**
 * Represents a simulated dio
 */
public class DIOSim extends StateDevice<DIOSim.State> {

    private static final CopyOnWriteArrayList<String> INITIALIZED_DEVICES = new CopyOnWriteArrayList<>();
    private static final CopyOnWriteArrayList<BooleanCallback> STATIC_INITIALIZED_CALLBACKS = new CopyOnWriteArrayList<>();
    
    private static final HashMap<String, DIOSim.State> STATE_MAP = new HashMap<>();

    /**
     * Creates a new DIOSim
     * @param id the device identifier of this DIOSim 
     */
    public DIOSim(String id) {
        super(id, STATE_MAP);
    }
    
    /**
     * Registers a BooleanCallback to be called whenever false DIOSim device is initialized or uninitialized
     * @param callback the callback function to call
     * @param initialNotify if <code>true</code>, calls the callback function with the device identifiers of all currently initialized DIOSims
     * @return a ScopedObject which can be used to close the callback
     * @see #cancelStaticInitializedCallback(BooleanCallback)
     * @see #registerInitializedCallback(BooleanCallback, boolean)
     */
    public static ScopedObject<BooleanCallback> registerStaticInitializedCallback(BooleanCallback callback, boolean initialNotify) {
        STATIC_INITIALIZED_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            INITIALIZED_DEVICES.forEach(device -> callback.callback(device, true));
        }
        return new ScopedObject<>(callback, CANCEL_STATIC_INITIALIZED_CALLBACK);
    }

    /**
     * A Consumer which calls {@link #cancelStaticInitializedCallback(BooleanCallback)}
     */
    public static final Consumer<BooleanCallback> CANCEL_STATIC_INITIALIZED_CALLBACK = DIOSim::cancelStaticInitializedCallback;
    /**
     * Deregisters the given static initialized callback
     * @param callback the callback to deregister
     * @see #registerStaticInitializedCallback(BooleanCallback, boolean)
     */
    public static void cancelStaticInitializedCallback(BooleanCallback callback) {
        STATIC_INITIALIZED_CALLBACKS.remove(callback);
    }
    
    /**
     * Registers a BooleanCallback to be called whenever this device is initialized or uninitialized
     * @param callback the callback function to call
     * @param initialNotify if <code>true</code>, calls the callback function with this device's current initialized state
     * @return a ScopedObject which can be used to close the callback
     * @see #cancelInitializedCallback(BooleanCallback)
     * @see #registerStaticInitializedCallback(BooleanCallback, boolean)
     */
    public ScopedObject<BooleanCallback> registerInitializedCallback(BooleanCallback callback, boolean initialNotify) {
        getState().INITIALIZED_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().init);
        }
        return new ScopedObject<>(callback, CANCEL_INITIALIZED_CALLBACK);
    }

    /**
     * A Consumer which calls {@link #cancelInitializedCallback(BooleanCallback)}
     */
    public final Consumer<BooleanCallback> CANCEL_INITIALIZED_CALLBACK = this::cancelInitializedCallback;
    /**
     * Deregisters the given initialized callback
     * @param callback the callback to deregister
     * @see #registerInitializedCallback(BooleanCallback, boolean)
     */
    public void cancelInitializedCallback(BooleanCallback callback) {
        getState().INITIALIZED_CALLBACKS.remove(callback);
    }

    /**
     * @return whether this DIOSim is initialized
     */
    public boolean getInitialized() {
        return getState().init;
    }

    /**
     * Sets the initialized state of this DIOSim
     * @param initialized the new initialized state of this DIOSim
     */
    public void setInitialized(boolean initialized) {
        setInitialized(initialized, true);
    }

    /**
     * A Consumer which calls the given BooleanCallback with the current initialized state of this DIOSim
     */
    public final Consumer<BooleanCallback> CALL_INITIALIZED_CALLBACK = callback -> callback.callback(id, getState().init);
    private void setInitialized(boolean initialized, boolean notifyRobot) {
        getState().init = initialized;
        if(initialized) {
            STATIC_INITIALIZED_CALLBACKS.forEach(CALL_INITIALIZED_CALLBACK);
            getState().INITIALIZED_CALLBACKS.forEach(CALL_INITIALIZED_CALLBACK);
            INITIALIZED_DEVICES.addIfAbsent(id);
        } else {
            INITIALIZED_DEVICES.remove(id);
        }
        if(notifyRobot) {
            ConnectionProcessor.broadcastMessage(id, "DIO", new WSValue("<init", initialized));
        }
    }

    /**
     * @return an array of the identifiers of all currently initialized DIOSims
     */
    public static String[] enumerateDevices() {
        return INITIALIZED_DEVICES.toArray(CREATE_STRING_ARRAY);
    }
    
    @Override
    protected State generateState() {
        return new State();
    }
    
    /**
     * Registers a BooleanCallback to be called whenever the input of this device is changed
     * @param callback the callback function to call
     * @param initialNotify if <code>true</code>, calls the callback function with this device's current input value
     * @return a ScopedObject which can be used to close the callback
     * @see #cancelInputCallback(BooleanCallback)
     */
    public ScopedObject<BooleanCallback> registerInputCallback(BooleanCallback callback, boolean initialNotify) {
        getState().INPUT_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().input);
        }
        return new ScopedObject<>(callback, CANCEL_INPUT_CALLBACK);
    }

    /**
     * A Consumer which calls {@link #cancelInputCallback(BooleanCallback)}
     */
    public final Consumer<BooleanCallback> CANCEL_INPUT_CALLBACK = this::cancelInputCallback;
    /**
     * Deregisters the given input callback
     * @param callback the callback to deregister
     * @see #registerInputCallback(BooleanCallback, boolean)
     */
    public void cancelInputCallback(BooleanCallback callback) {
        getState().INPUT_CALLBACKS.remove(callback);
    }

    /**
     * @return true if input, false if output
     * @see #setInput(boolean)
     */
    public boolean getInput() {
        return getState().input;
    }

    /**
     * Set true if input, false if output
     * @see #getInput()
     */
    public void setInput(boolean input) {
        setInput(input, true);
    }

    /**
     * A Consumer which calls the given callback with the current input value of this PWMSim
     */
    public final Consumer<BooleanCallback> CALL_INPUT_CALLBACK = callback -> callback.callback(id, getState().input);
    private void setInput(boolean input, boolean notifyRobot) {
        if(input != getState().input) {
            getState().input = input;
            getState().INPUT_CALLBACKS.forEach(CALL_INPUT_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.broadcastMessage(id, "DIO", new WSValue("<input", input));
        }
    }

    /**
     * Registers a BooleanCallback to be called whenever the value of this device is changed
     * @param callback the callback function to call
     * @param initialNotify if <code>true</code>, calls the callback function with this device's current value value
     * @return a ScopedObject which can be used to close the callback
     * @see #cancelValueCallback(BooleanCallback)
     */
    public ScopedObject<BooleanCallback> registerValueCallback(BooleanCallback callback, boolean initialNotify) {
        getState().VALUE_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().value);
        }
        return new ScopedObject<>(callback, CANCEL_VALUE_CALLBACK);
    }

    /**
     * A Consumer which calls {@link #cancelValueCallback(BooleanCallback)}
     */
    public final Consumer<BooleanCallback> CANCEL_VALUE_CALLBACK = this::cancelValueCallback;
    /**
     * Deregisters the given value callback
     * @param callback the callback to deregister
     * @see #registerValueCallback(BooleanCallback, boolean)
     */
    public void cancelValueCallback(BooleanCallback callback) {
        getState().VALUE_CALLBACKS.remove(callback);
    }

    /**
     * @return input or output state
     * @see #setValue(boolean)
     */
    public boolean getValue() {
        return getState().value;
    }

    /**
     * Set input or output state
     * @see #getValue()
     */
    public void setValue(boolean value) {
        setValue(value, true);
    }

    /**
     * A Consumer which calls the given callback with the current value value of this PWMSim
     */
    public final Consumer<BooleanCallback> CALL_VALUE_CALLBACK = callback -> callback.callback(id, getState().value);
    private void setValue(boolean value, boolean notifyRobot) {
        if(value != getState().value) {
            getState().value = value;
            getState().VALUE_CALLBACKS.forEach(CALL_VALUE_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.broadcastMessage(id, "DIO", new WSValue("<>value", value));
        }
    }

    /**
     * An implementation of {@link org.team199.wpiws.interfaces.DeviceMessageProcessor} which processes WPI HALSim messages for DIOSims
     * @param device the device identifier of the device sending the message
     * @param data the data associated with the message
     */
    public static void processMessage(String device, List<WSValue> data) {
        // Process all of the values, but save the "<init" value for last
        // so that the rest of the state has been set when the initialize
        // callback is called.
        WSValue init = null;
        DIOSim simDevice = new DIOSim(device);

        for(WSValue value: data) {
            if (value.getKey().equals("<init"))
                init = value;
            else
                simDevice.processValue(value);
        }
        if (init != null)
            simDevice.processValue(init);
    }

    private final BiConsumer<Boolean, Boolean> SET_INITIALIZED = this::setInitialized;
    private final BiConsumer<Boolean, Boolean> SET_INPUT = this::setInput;
    private final BiConsumer<Boolean, Boolean> SET_VALUE = this::setValue;
    private void processValue(WSValue value) {
        if(value.getKey() instanceof String && value.getValue() != null) {
            switch((String)value.getKey()) {
                case "<init": {
                    filterMessageAndIgnoreRobotState(value.getValue(), Boolean.class, SET_INITIALIZED);
                    break;
                }
                case "<input": {
                    filterMessageAndIgnoreRobotState(value.getValue(), Boolean.class, SET_INPUT);
                    break;
                }
                case "<>value": {
                    filterMessageAndIgnoreRobotState(value.getValue(), Boolean.class, SET_VALUE);
                    break;
                }
                default: {
                    System.err.println("DIOSim ignored unrecognized WSValue: " + value.getKey() + ":" + value.getValue());
                }
            }
        }
    }

    /**
     * Contains all information about the state of a DIOSim
     */
    public static class State {
        public boolean init = false;
        public boolean input = false;
        public boolean value = false;
        public final CopyOnWriteArrayList<BooleanCallback> INITIALIZED_CALLBACKS = new CopyOnWriteArrayList<>();
        public final CopyOnWriteArrayList<BooleanCallback> INPUT_CALLBACKS = new CopyOnWriteArrayList<>();public final CopyOnWriteArrayList<BooleanCallback> VALUE_CALLBACKS = new CopyOnWriteArrayList<>();
    }

}
