// PLEASE DO NOT EDIT THIS FILE!!!
// This file is auto-generated by https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate
// To regenerate please run:
// 'ag -o "WebotsWebSocketsImpl/src/main/org/team199/wpiws/devices" "<path/to/wpilib-ws.yaml>" "https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate.git"'
package org.team199.wpiws.devices;

import java.util.HashMap;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

import org.team199.wpiws.ScopedObject;
import org.team199.wpiws.StateDevice;
import org.team199.wpiws.connection.ConnectionProcessor;
import org.team199.wpiws.connection.WSValue;
import org.team199.wpiws.interfaces.*;

public class DutyCycleSim extends StateDevice<DutyCycleSim.State> {

    private static final HashMap<String, DutyCycleSim.State> STATE_MAP = new HashMap<>();

    public DutyCycleSim(String id) {
        super(id, STATE_MAP);
    }
    
    @Override
    protected State generateState() {
        return new State();
    }
    
    public ScopedObject<BooleanCallback> registerConnectedCallback(BooleanCallback callback, boolean initialNotify) {
        getState().CONNECTED_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().connected);
        }
        return new ScopedObject<>(callback, CANCEL_CONNECTED_CALLBACK);
    }

    public final Consumer<BooleanCallback> CANCEL_CONNECTED_CALLBACK = this::cancelConnectedCallback;
    public void cancelConnectedCallback(BooleanCallback callback) {
        getState().CONNECTED_CALLBACKS.remove(callback);
    }

    public boolean getConnected() {
        return getState().connected;
    }

    public void setConnected(boolean connected) {
        setConnected(connected, true);
    }

    public final Consumer<BooleanCallback> CALL_CONNECTED_CALLBACK = callback -> callback.callback(id, getState().connected);
    private void setConnected(boolean connected, boolean notifyRobot) {
        if(connected != getState().connected) {
            getState().connected = connected;
            getState().CONNECTED_CALLBACKS.forEach(CALL_CONNECTED_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.brodcastMessage(id, "DutyCycle", new WSValue(">connected", connected));
        }
    }

    public ScopedObject<DoubleCallback> registerPositionCallback(DoubleCallback callback, boolean initialNotify) {
        getState().POSITION_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().position);
        }
        return new ScopedObject<>(callback, CANCEL_POSITION_CALLBACK);
    }

    public final Consumer<DoubleCallback> CANCEL_POSITION_CALLBACK = this::cancelPositionCallback;
    public void cancelPositionCallback(DoubleCallback callback) {
        getState().POSITION_CALLBACKS.remove(callback);
    }

    public double getPosition() {
        return getState().position;
    }

    public void setPosition(double position) {
        setPosition(position, true);
    }

    public final Consumer<DoubleCallback> CALL_POSITION_CALLBACK = callback -> callback.callback(id, getState().position);
    private void setPosition(double position, boolean notifyRobot) {
        if(position != getState().position) {
            getState().position = position;
            getState().POSITION_CALLBACKS.forEach(CALL_POSITION_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.brodcastMessage(id, "DutyCycle", new WSValue(">position", position));
        }
    }

    public static void processMessage(String device, List<WSValue> data) {
        DutyCycleSim simDevice = new DutyCycleSim(device);
        for(WSValue value: data) {
            simDevice.processValue(value);
        }
    }

    private final BiConsumer<Boolean, Boolean> SET_CONNECTED = this::setConnected;
    private final BiConsumer<Double, Boolean> SET_POSITION = this::setPosition;
    private void processValue(WSValue value) {
        if(value.getKey() instanceof String && value.getValue() != null) {
            switch((String)value.getKey()) {
                
                case ">connected": {
                    filterMessageAndIgnoreRobotState(value.getValue(), Boolean.class, SET_CONNECTED);
                    break;
                }
                case ">position": {
                    filterMessageAndIgnoreRobotState(value.getValue(), Double.class, SET_POSITION);
                    break;
                }
            }
        }
    }

    public static class State {
        public boolean connected = false;
        public double position = 0;
        public final CopyOnWriteArrayList<BooleanCallback> CONNECTED_CALLBACKS = new CopyOnWriteArrayList<>();public final CopyOnWriteArrayList<DoubleCallback> POSITION_CALLBACKS = new CopyOnWriteArrayList<>();
    }

}