// PLEASE DO NOT EDIT THIS FILE!!!
// This file is auto-generated by https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate
// To regenerate please run:
// 'ag -o "WebotsWebSocketsImpl/src/main/org/team199/wpiws/devices" "<path/to/wpilib-ws.yaml>" "https://github.com/DeepBlueRobotics/WPIWebSocketsTemplate.git"'
package org.team199.wpiws.devices;

import java.util.HashMap;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

import org.team199.wpiws.ScopedObject;
import org.team199.wpiws.StateDevice;
import org.team199.wpiws.connection.ConnectionProcessor;
import org.team199.wpiws.connection.WSValue;
import org.team199.wpiws.interfaces.*;

public class JoystickSim extends StateDevice<JoystickSim.State> {

    private static final HashMap<String, JoystickSim.State> STATE_MAP = new HashMap<>();

    public JoystickSim(String id) {
        super(id, STATE_MAP);
    }
    
    @Override
    protected State generateState() {
        return new State();
    }
    
    public ScopedObject<DoubleArrayCallback> registerAxesCallback(DoubleArrayCallback callback, boolean initialNotify) {
        getState().AXES_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().axes);
        }
        return new ScopedObject<>(callback, CANCEL_AXES_CALLBACK);
    }

    public final Consumer<DoubleArrayCallback> CANCEL_AXES_CALLBACK = this::cancelAxesCallback;
    public void cancelAxesCallback(DoubleArrayCallback callback) {
        getState().AXES_CALLBACKS.remove(callback);
    }

    public double[] getAxes() {
        return getState().axes;
    }

    public void setAxes(double[] axes) {
        setAxes(axes, true);
    }

    public final Consumer<DoubleArrayCallback> CALL_AXES_CALLBACK = callback -> callback.callback(id, getState().axes);
    private void setAxes(double[] axes, boolean notifyRobot) {
        if(axes != getState().axes) {
            getState().axes = axes;
            getState().AXES_CALLBACKS.forEach(CALL_AXES_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.brodcastMessage(id, "Joystick", new WSValue(">axes", axes));
        }
    }

    public ScopedObject<IntegerArrayCallback> registerPovsCallback(IntegerArrayCallback callback, boolean initialNotify) {
        getState().POVS_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().povs);
        }
        return new ScopedObject<>(callback, CANCEL_POVS_CALLBACK);
    }

    public final Consumer<IntegerArrayCallback> CANCEL_POVS_CALLBACK = this::cancelPovsCallback;
    public void cancelPovsCallback(IntegerArrayCallback callback) {
        getState().POVS_CALLBACKS.remove(callback);
    }

    public int[] getPovs() {
        return getState().povs;
    }

    public void setPovs(int[] povs) {
        setPovs(povs, true);
    }

    public final Consumer<IntegerArrayCallback> CALL_POVS_CALLBACK = callback -> callback.callback(id, getState().povs);
    private void setPovs(int[] povs, boolean notifyRobot) {
        if(povs != getState().povs) {
            getState().povs = povs;
            getState().POVS_CALLBACKS.forEach(CALL_POVS_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.brodcastMessage(id, "Joystick", new WSValue(">povs", povs));
        }
    }

    public ScopedObject<BooleanArrayCallback> registerButtonsCallback(BooleanArrayCallback callback, boolean initialNotify) {
        getState().BUTTONS_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().buttons);
        }
        return new ScopedObject<>(callback, CANCEL_BUTTONS_CALLBACK);
    }

    public final Consumer<BooleanArrayCallback> CANCEL_BUTTONS_CALLBACK = this::cancelButtonsCallback;
    public void cancelButtonsCallback(BooleanArrayCallback callback) {
        getState().BUTTONS_CALLBACKS.remove(callback);
    }

    public boolean[] getButtons() {
        return getState().buttons;
    }

    public void setButtons(boolean[] buttons) {
        setButtons(buttons, true);
    }

    public final Consumer<BooleanArrayCallback> CALL_BUTTONS_CALLBACK = callback -> callback.callback(id, getState().buttons);
    private void setButtons(boolean[] buttons, boolean notifyRobot) {
        if(buttons != getState().buttons) {
            getState().buttons = buttons;
            getState().BUTTONS_CALLBACKS.forEach(CALL_BUTTONS_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.brodcastMessage(id, "Joystick", new WSValue(">buttons", buttons));
        }
    }

    public ScopedObject<DoubleCallback> registerRumbleLeftCallback(DoubleCallback callback, boolean initialNotify) {
        getState().RUMBLELEFT_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().rumbleleft);
        }
        return new ScopedObject<>(callback, CANCEL_RUMBLELEFT_CALLBACK);
    }

    public final Consumer<DoubleCallback> CANCEL_RUMBLELEFT_CALLBACK = this::cancelRumbleLeftCallback;
    public void cancelRumbleLeftCallback(DoubleCallback callback) {
        getState().RUMBLELEFT_CALLBACKS.remove(callback);
    }

    public double getRumbleLeft() {
        return getState().rumbleleft;
    }

    public void setRumbleLeft(double rumbleleft) {
        setRumbleLeft(rumbleleft, true);
    }

    public final Consumer<DoubleCallback> CALL_RUMBLELEFT_CALLBACK = callback -> callback.callback(id, getState().rumbleleft);
    private void setRumbleLeft(double rumbleleft, boolean notifyRobot) {
        if(rumbleleft != getState().rumbleleft) {
            getState().rumbleleft = rumbleleft;
            getState().RUMBLELEFT_CALLBACKS.forEach(CALL_RUMBLELEFT_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.brodcastMessage(id, "Joystick", new WSValue("<rumble_left", rumbleleft));
        }
    }

    public ScopedObject<DoubleCallback> registerRumbleRightCallback(DoubleCallback callback, boolean initialNotify) {
        getState().RUMBLERIGHT_CALLBACKS.addIfAbsent(callback);
        if(initialNotify) {
            callback.callback(id, getState().rumbleright);
        }
        return new ScopedObject<>(callback, CANCEL_RUMBLERIGHT_CALLBACK);
    }

    public final Consumer<DoubleCallback> CANCEL_RUMBLERIGHT_CALLBACK = this::cancelRumbleRightCallback;
    public void cancelRumbleRightCallback(DoubleCallback callback) {
        getState().RUMBLERIGHT_CALLBACKS.remove(callback);
    }

    public double getRumbleRight() {
        return getState().rumbleright;
    }

    public void setRumbleRight(double rumbleright) {
        setRumbleRight(rumbleright, true);
    }

    public final Consumer<DoubleCallback> CALL_RUMBLERIGHT_CALLBACK = callback -> callback.callback(id, getState().rumbleright);
    private void setRumbleRight(double rumbleright, boolean notifyRobot) {
        if(rumbleright != getState().rumbleright) {
            getState().rumbleright = rumbleright;
            getState().RUMBLERIGHT_CALLBACKS.forEach(CALL_RUMBLERIGHT_CALLBACK);
        }
        if(notifyRobot) {
            ConnectionProcessor.brodcastMessage(id, "Joystick", new WSValue("<rumble_right", rumbleright));
        }
    }

    public static void processMessage(String device, List<WSValue> data) {
        JoystickSim simDevice = new JoystickSim(device);
        for(WSValue value: data) {
            simDevice.processValue(value);
        }
    }

    private final BiConsumer<double[], Boolean> SET_AXES = this::setAxes;
    private final BiConsumer<int[], Boolean> SET_POVS = this::setPovs;
    private final BiConsumer<boolean[], Boolean> SET_BUTTONS = this::setButtons;
    private final BiConsumer<Double, Boolean> SET_RUMBLELEFT = this::setRumbleLeft;
    private final BiConsumer<Double, Boolean> SET_RUMBLERIGHT = this::setRumbleRight;
    private void processValue(WSValue value) {
        if(value.getKey() instanceof String && value.getValue() != null) {
            switch((String)value.getKey()) {
                
                case ">axes": {
                    filterMessageAndIgnoreRobotState(value.getValue(), double[].class, SET_AXES);
                    break;
                }
                case ">povs": {
                    filterMessageAndIgnoreRobotState(value.getValue(), int[].class, SET_POVS);
                    break;
                }
                case ">buttons": {
                    filterMessageAndIgnoreRobotState(value.getValue(), boolean[].class, SET_BUTTONS);
                    break;
                }
                case "<rumble_left": {
                    filterMessageAndIgnoreRobotState(value.getValue(), Double.class, SET_RUMBLELEFT);
                    break;
                }
                case "<rumble_right": {
                    filterMessageAndIgnoreRobotState(value.getValue(), Double.class, SET_RUMBLERIGHT);
                    break;
                }
            }
        }
    }

    public static class State {
        public double[] axes = new double[0];
        public int[] povs = new int[0];
        public boolean[] buttons = new boolean[0];
        public double rumbleleft = 0;
        public double rumbleright = 0;
        public final CopyOnWriteArrayList<DoubleArrayCallback> AXES_CALLBACKS = new CopyOnWriteArrayList<>();public final CopyOnWriteArrayList<IntegerArrayCallback> POVS_CALLBACKS = new CopyOnWriteArrayList<>();public final CopyOnWriteArrayList<BooleanArrayCallback> BUTTONS_CALLBACKS = new CopyOnWriteArrayList<>();public final CopyOnWriteArrayList<DoubleCallback> RUMBLELEFT_CALLBACKS = new CopyOnWriteArrayList<>();public final CopyOnWriteArrayList<DoubleCallback> RUMBLERIGHT_CALLBACKS = new CopyOnWriteArrayList<>();
    }

}
