{% set pfname = propName | safe %}
{% set pname = pfname | formatPropName %}
{% set pnamel = pname | lower %}
{% set pnameu = pname | upper %}
{% set ptype = prop | formatPropType(name, propName) %}
{% set pobjtype = prop | formatPropObjType(name, propName) %}
{% set callbackType = prop | formatPropCallbackType(name, propName) | safe %}
{% set parser = prop | formatPropParser(name, propName) %}
{% set pinit = prop | formatPropInitialValue(name, propName) | safe %}
{% set isRobotInput = pfname | isRobotInput %}
{% set isRobotOutput = pfname | isRobotOutput %}
